

export default [
    {
      id: 1,
      prodpic: "./images/kabraaas.jpeg",
      title: "Kabrass Sugar",
      quantity: 2,
      price: 230,
      available: 6,
      isFav:true,
    },
    {
      id: 2,
      prodpic: "./images/indomie.jpg",
      title: "Indomie",
      price: 25,
      quantity: 1,
      available: 1,
      isFav:false,
    },
    {
      id: 3,
      prodpic: "./images/packshot_cof_cup.jpg",
      title: "Cups",
      quantity: 1,
      price: 470,
      available: 0,
      isFav:false,
    },
    {
      id: 4,
      prodpic: "./images/pishori.jpeg",
      title: "Pishori Rice",
      quantity: 2,
      price: 520,
      available: 0,
      isFav:false,
    },
    {
      id: 5,
      prodpic: "./images/plates.jpeg",
      title: "Glass Plates",
      quantity: 4,
      price: 230,
      available: 12,
      isFav:false,
    },
    {
      id: 6,
      prodpic: "./images/DETTOL-OG-SOAP.jpg",
      title: "Detol Soap",
      price: 654,
      quantity: 2,
      available: 0,
      isFav:false,
    },
    {
      id: 7,
      prodpic: "./images/Daawat-Spaghetti-Green-Label.jpg",
      title: "Dawati Suparghetti",
      quantity: 1,
      price: 180,
      available: 1,
      isFav:false,
    },
    {
      id: 8,
      prodpic: "./images/Aerial.jpeg",
      title: "Ariel",
      quantity: 2,
      price: 670,
      available: 0,
      isFav:false,
    },
  
    {
      id: 9,
      prodpic: "./images/COoking oil.jpeg",
      title: "Fresh fry",
      quantity: 2,
      price: 622,
      available: 700,
      isFav:false,
    },
  
    {
      id: 10,
      prodpic: "./images/Cooking oil10lts.jpeg",
      title: "Post Man cooking oil",
      quantity: 1,
      price: 1100,
      available: 100,
      isFav:false,
    },
  
    {
      id: 11,
      prodpic: "./images/f9.jpeg",
      title: "F9 Ear Pods",
      quantity: 1,
      price: 1670,
      available: 12,
      isFav:false,
    },
  
    {
      id: 12,
      prodpic: "./images/iphone14.jpeg",
      title: "IPhone 14",
      quantity: 1,
      price: 345007,
      available: 12,
      isFav:false,
    },
    {
      id: 13,
      prodpic: "./images/J4.jpeg",
      title: "Jordan 4 PSG Air",
      quantity: 1,
      price: 4620,
      available: 12,
      isFav:false,
    },
  
    {
      id: 14,
      prodpic: "./images/laptopbag.png",
      title: "Premium Laptop Bag",
      quantity: 1,
      price: 2381,
      available: 12,
      isFav:false,
    },
  
    {
      id: 15,
      prodpic: "./images/f9.jpeg",
      title: "F9 Ear Pods",
      quantity: 1,
      price: 1430,
      available: 12,
      isFav:false,
    },
  
    {
      id: 16,
      prodpic: "./images/menshoes.jpeg",
      title: "New Leather Men Shoes",
      quantity: 1,
      price: 1989,
      available: 0,
      isFav:false,
    },
  
    {
      id: 17,
      prodpic: "./images/Nivea.jpeg",
      title: "Nivea New Body Lotion.",
      quantity: 1,
      price: 930,
      available: 124,
      isFav:false,
    },
  
    {
      id: 18,
      prodpic: "./images/laptopbag.png",
      title: "New laptop Bag",
      quantity: 1,
      price: 2270,
      available: 12,
      isFav:false,
    },
  
    {
      id: 19,
      prodpic: "./images/nokia2.4.jpeg",
      title: "Nokia 2.4 new",
      quantity: 1,
      price: 18340,
      available: 3,
      isFav:false,
    },
    {
      id: 20,
      prodpic: "./images/SoundBar.jpeg",
      title: "Sound Bar  17''",
      quantity: 1,
      price: 74000,
      available: 1,
      isFav:false,
    },
  
    {
      id: 21,
      prodpic: "./images/suitcase.jpeg",
      title: "Brown Travel Suit Case",
      quantity: 1,
      price: 4698,
      available: 4,
      isFav:false,
  
    },
  
    {
      id: 22,
      prodpic: "./images/sumsungzflip.jpeg",
      title: "Sumsung Galaxy Zflip",
      quantity: 1,
      price: 79877,
      available: 2,
      isFav:false,
    },
  ];
  